2019-03-23 19:28:42.317 [error] <0.1140.0>@Elixir.SmartPetFeederApp.RabbitMQ:connection_setup:373 CRASH REPORT Process <0.1140.0> with 0 neighbours crashed with reason: no match of right hand value {error,unknown_host} in 'Elixir.SmartPetFeederApp.RabbitMQ':connection_setup/0 line 373
2019-03-23 19:28:42.318 [error] <0.1002.0>@Elixir.SmartPetFeederApp.RabbitMQ:connection_setup:373 Supervisor 'Elixir.SmartPetFeederApp.Supervisor' had child 'Elixir.SmartPetFeederApp.RabbitMQ' started with 'Elixir.SmartPetFeederApp.RabbitMQ':start_link([]) at undefined exit with reason no match of right hand value {error,unknown_host} in 'Elixir.SmartPetFeederApp.RabbitMQ':connection_setup/0 line 373 in context start_error
2019-03-23 19:28:42.323 [error] <0.1000.0> CRASH REPORT Process <0.1000.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.SmartPetFeederApp.RabbitMQ',{{badmatch,{error,unknown_host}},[{'Elixir.SmartPetFeederApp.RabbitMQ',connection_setup,0,[{file,"lib/smart_pet_feeder_app/communication/rabbitmq.ex"},{line,373}]},{'Elixir.SmartPetFeederApp.RabbitMQ',init,1,[{file,"lib/smart_pet_feeder_app/communication/rabbitmq.ex"},{line,187}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 138
